---
- name: "Loading projects properties"
  include_role:
    name: load_maven_properties

- name: "Extend parent `pom.xml` with 'datasource' module"
  include_role:
    name: insert_template_after_another
  with_items:
    - path: "{{ app_basedir }}/pom.xml"
      insert_after_template: "{{ role_path }}/templates/parent/insert_after_template.j2"
      insert_template: "{{ role_path }}/templates/parent/insert_template.j2"
  loop_control:
    loop_var: cs_itaa_tmpl_item


- name: "Update the `domain` module with dependency on `datasource`"
  include_role:
    name: insert_template_after_another
  with_items:
    - path: "{{ app_basedir }}/domain/pom.xml"
      insert_after_template: "{{ role_path }}/templates/domain/insert_after_template.j2"
      insert_template: "{{ role_path }}/templates/domain/insert_template.j2"
  loop_control:
    loop_var: cs_itaa_tmpl_item

- name: "Update the `deps` module with the dependencies of `datasource`"
  include_role:
    name: insert_template_after_another
  with_items:
    - path: "{{ app_basedir }}/deps/pom.xml"
      insert_after_template: "{{ role_path }}/templates/deps/properties/insert_after_template.j2"
      insert_template: "{{ role_path }}/templates/deps/properties/insert_template.j2"
    - path: "{{ app_basedir }}/deps/pom.xml"
      insert_after_template: "{{ role_path }}/templates/deps/spring_data_jpa/insert_after_template.j2"
      insert_template: "{{ role_path }}/templates/deps/spring_data_jpa/insert_template.j2"
    - path: "{{ app_basedir }}/deps/pom.xml"
      insert_after_template: "{{ role_path }}/templates/deps/liquibase/insert_after_template.j2"
      insert_template: "{{ role_path }}/templates/deps/liquibase/insert_template.j2"
  loop_control:
    loop_var: cs_itaa_tmpl_item

- name: "Generate the `datasource` module"
  include_role:
    name: gen_java_class_from_path
  with_items:
    - src: "{{ role_path }}/templates/datasource"
      dst_src_path: "{{ app_basedir }}/datasource"
  loop_control:
    loop_var: cs_gjcfp_templates