---
- name: "Update the deps `pom.xml` with enunciate version"
  include_role:
    name: insert_text_after_another
  loop_control:
    loop_var: cs_itaa_txt_item
  with_items:
    - path: "{{ app_basedir }}/deps/pom.xml"
      insert_after: |
        </resteasy.version>
      insert_text: |4

              <!-- Must be the same as `enunciate-plugin.version` in the parent pom-->
              <!-- and as in enunciate.xml:-->
              <!-- ... http://enunciate.webcohesion.com/schemas/enunciate-{{ enunciate_version }}.xsd-->
              <enunciate.version>{{ enunciate_version }}</enunciate.version>

- name: "Update the deps `pom.xml` file with dependencies"
  include_role:
    name: insert_template_after_another
  with_items:
    - path: "{{ app_basedir }}/deps/pom.xml"
      insert_after_template: "{{ role_path }}/templates/deps/enunciate/insert_after_template.j2"
      insert_template: "{{ role_path }}/templates/deps/enunciate/insert_template.j2"
  loop_control:
    loop_var: cs_itaa_tmpl_item
