---
- name: "Loading projects properties"
  include_role:
    name: load_maven_properties

- import_tasks: tasks/deps.yaml

- import_tasks: tasks/parent_pom.yaml

- name: "Generate sources of `rest_api` module"
  include_role:
    name: gen_java_class_from_path
  with_items:
    - src: "{{ role_path }}/templates/rest_api"
      dst_src_path: "{{ app_basedir }}/rest_api"
    - src: "{{ role_path }}/templates/rest_web"
      dst_src_path: "{{ app_basedir }}/rest_web"

# special hack, just to append file with the content
- name: "Update `README.md`"
  include_role:
    name: insert_template_after_another
  with_items:
    - path: "{{ app_basedir }}/README.md"
      insert_after_template: "{{ role_path }}/templates/readme/insert_template.j2"
      insert_template: "{{ role_path }}/templates/readme/insert_template.j2"
