---
- name: "Create `deps` folder if does not exist"
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  with_items:
    - "{{ app_basedir }}/deps"


- name: "Generate deps/pom.xml file"
  template:
    src: "{{ item }}.j2"
    dest: "{{ app_basedir }}/{{ item }}"
    mode: 0644
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    force: yes
  with_items:
    - deps/pom.xml