---
- name: "Generate config java classes for `rest_api` module"
  include_role:
    name: gen_java_class_from_template
  with_items:
    - src: rest_api/src/main/java/ConfigRestApi.java.j2
      dst: "{{ app_basedir }}/rest_api/src/main/java/{{ group_id_path }}/rest/api/ConfigRestApi.java"
  loop_control:
    loop_var: cs_gjcft_item
