---
- name: "Ansible check for `jpa_datasource` module."
  stat:
    path: "{{ mvn_project_basedir }}/jpa_datasource"
  register: jpa_datasource_path

- block:

  - name: Load shared variables
    include_vars: "{{ mvn_project_basedir }}/.ansible/ansible_shared_variables.yml"

  - import_tasks: tasks/jpa_datasource.yml

  when: not jpa_datasource_path.stat.exists

- debug:
    msg:
      - "ERROR: '{{ mvn_project_basedir }}/jpa_datasource' already exist"
      - "       To generate 'jpa_datasource' module first delete the previous one."
  when: jpa_datasource_path.stat.exists