---
- name: "Create `commons_jax_rs_client` folder if does not exist"
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  with_items:
    - "{{ app_basedir }}/commons_jax_rs_client"

- name: "Generate files into `commons_jax_rs_client` folder"
  template:
    src: "{{ item }}.j2"
    dest: "{{ app_basedir }}/commons_jax_rs_client/{{ item }}"
    mode: 0644
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    force: yes
  with_items:
    - pom.xml
    - README.md

- name: "Generate java classes of `commons_jax_rs_client` module"
  include_role:
    name: gen_java_class_from_template
  with_items:
    - src: src/main/java/JaxRsProxyConfig.java.j2
      dst: "{{ app_basedir }}/commons_jax_rs_client/src/main/java/{{ group_id_path }}/commons/jax/rs/client/JaxRsProxyConfig.java"
    - src: src/main/java/JaxRsProxyConfigBuilder.java.j2
      dst: "{{ app_basedir }}/commons_jax_rs_client/src/main/java/{{ group_id_path }}/commons/jax/rs/client/JaxRsProxyConfigBuilder.java"
    - src: src/main/java/JaxRsExceptionsUtils.java.j2
      dst: "{{ app_basedir }}/commons_jax_rs_client/src/main/java/{{ group_id_path }}/commons/jax/rs/client/JaxRsExceptionsUtils.java"
    - src: src/main/java/filter/JacksonProvider.java.j2
      dst: "{{ app_basedir }}/commons_jax_rs_client/src/main/java/{{ group_id_path }}/commons/jax/rs/client/filter/JacksonProvider.java"
    - src: src/main/java/filter/LogDebugFilter.java.j2
      dst: "{{ app_basedir }}/commons_jax_rs_client/src/main/java/{{ group_id_path }}/commons/jax/rs/client/filter/LogDebugFilter.java"
    - src: src/main/java/filter/LogErrorFilter.java.j2
      dst: "{{ app_basedir }}/commons_jax_rs_client/src/main/java/{{ group_id_path }}/commons/jax/rs/client/filter/LogErrorFilter.java"
    - src: src/main/java/filter/RequestResponseInfo.java.j2
      dst: "{{ app_basedir }}/commons_jax_rs_client/src/main/java/{{ group_id_path }}/commons/jax/rs/client/filter/RequestResponseInfo.java"
    - src: src/main/java/filter/AuthClientRequestFilterFactory.java.j2
      dst: "{{ app_basedir }}/commons_jax_rs_client/src/main/java/{{ group_id_path }}/commons/jax/rs/client/filter/AuthClientRequestFilterFactory.java"

