---
- debug:
    msg: "Current project folder for project generation: `{{ mvn_project_basedir }}`"
    verbosity: 1

- import_tasks: tasks/code_quality.yml

- import_tasks: tasks/parent_module.yml

- import_tasks: tasks/deps_module.yml

- import_tasks: tasks/domain_api_module.yml

- import_tasks: tasks/domain_module.yml

- import_tasks: tasks/rest_api_module.yml

- import_tasks: tasks/front_end_war_module.yml
