---
- name: "Generate parent `pom.xml` file"
  template:
    src: "{{ item }}.j2"
    dest: "{{ mvn_project_basedir }}/{{ item }}"
    mode: 0644
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    force: yes
  with_items:
    - pom.xml

- name: "Add `.gitignore` file"
  template:
    src: ".gitignore"
    dest: "{{ mvn_project_basedir }}/.gitignore"
    mode: 0644
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    force: yes