---
- name: "Create `commons_cron` folder if does not exist"
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  with_items:
    - "{{ mvn_project_basedir }}/commons_cron"

- name: "Generate files into `commons_cron` folder"
  template:
    src: "{{ item }}.j2"
    dest: "{{ mvn_project_basedir }}/{{ item }}"
    mode: 0644
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    force: yes
  with_items:
    - commons_cron/pom.xml
    - commons_cron/README.md

- name: "Add main sources to `commons_cron` module"
  include_role:
    name: gen_java_class_from_template
  with_items:
    - src: commons_cron/src/main/java/CronService.java.j2
      dst: "{{ mvn_project_basedir }}/commons_cron/src/main/java/{{ group_id_path }}/commons/cron/CronService.java"
    - src: commons_cron/src/main/java/Executor.java.j2
      dst: "{{ mvn_project_basedir }}/commons_cron/src/main/java/{{ group_id_path }}/commons/cron/Executor.java"
    - src: commons_cron/src/main/java/Timer.java.j2
      dst: "{{ mvn_project_basedir }}/commons_cron/src/main/java/{{ group_id_path }}/commons/cron/Timer.java"
    - src: commons_cron/src/main/resources/META-INF/beans.xml
      dst: "{{ mvn_project_basedir }}/commons_cron/src/main/resources/META-INF/beans.xml"

- name: "Add test sources to `commons_cron` module"
  include_role:
    name: gen_java_class_from_template
  with_items:
    - src: commons_cron/src/test/java/TimerTest.java.j2
      dst: "{{ mvn_project_basedir }}/commons_cron/src/test/java/{{ group_id_path }}/commons/cron/TimerTest.java"