---
- name: "Generate cron rest service for `front_end_war` module"
  include_role:
    name: gen_java_class_from_template
  with_items:
    - src: front_end_war/src/main/java/rest/TimerRestService.java.j2
      dst: "{{ mvn_project_basedir }}/front_end_war/src/main/java/{{ group_id_path }}/rest/app/TimerRestService.java"

- name: "Update jax rs configuration with new config service"
  include_role:
    name: insert_template_after_another
  with_items:
    - path: "{{ mvn_project_basedir }}/front_end_war/src/main/java/{{ group_id_path }}/rest/config/JAXRSConfiguration.java"
      insert_after_template: "{{ role_path }}/templates/front_end_war/src/main/java/rest/config/import_insert_after.j2"
      insert_template: "{{ role_path }}/templates/front_end_war/src/main/java/rest/config/import_insert.j2"
    - path: "{{ mvn_project_basedir }}/front_end_war/src/main/java/{{ group_id_path }}/rest/config/JAXRSConfiguration.java"
      insert_after_template: "{{ role_path }}/templates/front_end_war/src/main/java/rest/config/jax_rs_config_insert_after.j2"
      insert_template: "{{ role_path }}/templates/front_end_war/src/main/java/rest/config/jax_rs_config_insert.j2"
