---
- name: "Loading projects properties"
  include_role:
    name: load_maven_properties

- name: "Add main sources to `commons_cron` module"
  include_role:
    name: gen_java_class_from_path
  with_items:
    - src: "{{ role_path }}/templates/commons_cron"
      dst_src_path: "{{ app_basedir }}/commons_cron"
  loop_control:
    loop_var: cs_gjcfp_templates

- name: "Add 'commons_cron' module in parent"
  include_role:
    name: insert_text_after_another
  loop_control:
    loop_var: cs_itaa_txt_item
  with_items:
    - path: "{{ app_basedir }}/pom.xml"
      insert_after: |
        <module>deps</module>
      insert_text: |4
              <module>commons_cron</module>

- name: "Add dependencies on 'commons_cron' module"
  include_role:
    name: insert_template_after_another
  with_items:
    - path: "{{ app_basedir }}/domain/pom.xml"
      insert_after_template: "{{ role_path }}/templates/domain/deps/insert_after_template.j2"
      insert_template: "{{ role_path }}/templates/domain/deps/insert_template.j2"
  loop_control:
    loop_var: cs_itaa_tmpl_item

- name: "Add cron service example to `domain` module"
  include_role:
    name: gen_java_class_from_template
  with_items:
    - src: domain/src/main/java/ApplicationTimer.java.j2
      dst: "{{ app_basedir }}/domain/src/main/java/{{ group_id_path }}/cron/ApplicationTimer.java"
  loop_control:
    loop_var: cs_gjcft_item

- name: "Add rest api interface"
  include_role:
    name: insert_template_after_another
  with_items:
    - path: "{{ app_basedir }}/rest_api/pom.xml"
      insert_after_template: "{{ role_path }}/templates/rest_api/deps/insert_after_template.j2"
      insert_template: "{{ role_path }}/templates/rest_api/deps/insert_template.j2"
  loop_control:
    loop_var: cs_itaa_tmpl_item

- name: "Add cron service rest api to `rest_api` module"
  include_role:
    name: gen_java_class_from_template
  with_items:
    - src: rest_api/src/main/java/TimerRestApi.java.j2
      dst: "{{ app_basedir }}/rest_api/src/main/java/{{ group_id_path }}/rest/api/TimerRestApi.java"
  loop_control:
    loop_var: cs_gjcft_item

- import_tasks: tasks/rest_web.yaml