---
- name: "Add dependencies on 'commons_cron' module"
  include_role:
    name: insert_template_after_another
  with_items:
    - path: "{{ mvn_project_basedir }}/pom.xml"
      insert_after_template: "{{ role_path }}/templates/parent/insert_after_template.j2"
      insert_template: "{{ role_path }}/templates/parent/insert_template.j2"