---
- name: "Add dependencies on 'commons_cron' module"
  include_role:
    name: insert_template_after_another
  with_items:
    - path: "{{ mvn_project_basedir }}/rest_api/pom.xml"
      insert_after_template: "{{ role_path }}/templates/rest_api/deps/insert_after_template.j2"
      insert_template: "{{ role_path }}/templates/rest_api/deps/insert_template.j2"

- name: "Add cron service rest api to `rest_api` module"
  include_role:
    name: gen_java_class_from_template
  with_items:
    - src: rest_api/src/main/java/TimerRestApi.java.j2
      dst: "{{ mvn_project_basedir }}/rest_api/src/main/java/{{ group_id_path }}/rest/api/TimerRestApi.java"
