---
- name: "Create `commons_jax_ws_client` folder if does not exist"
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  with_items:
    - "{{ mvn_project_basedir }}/commons_jax_ws_client"

- name: "Generate files into `commons_jax_ws_client` folder"
  template:
    src: "{{ item }}.j2"
    dest: "{{ mvn_project_basedir }}/commons_jax_ws_client/{{ item }}"
    mode: 0644
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    force: yes
  with_items:
    - pom.xml
    - README.md

- name: "Add dependencies on 'commons_jax_ws_client' module"
  include_role:
    name: insert_template_after_another
  with_items:
    - path: "{{ mvn_project_basedir }}/pom.xml"
      insert_after_template: "{{ role_path }}/templates/deps/parent/insert_after_template.j2"
      insert_template: "{{ role_path }}/templates/deps/parent/insert_template.j2"
    - path: "{{ mvn_project_basedir }}/deps/pom.xml"
      insert_after_template: "{{ role_path }}/templates/deps/deps/properties/insert_after_template.j2"
      insert_template: "{{ role_path }}/templates/deps/deps/properties/insert_template.j2"
    - path: "{{ mvn_project_basedir }}/deps/pom.xml"
      insert_after_template: "{{ role_path }}/templates/deps/deps/apache_cxf/insert_after_template.j2"
      insert_template: "{{ role_path }}/templates/deps/deps/apache_cxf/insert_template.j2"

- name: "Generate java classes of `commons_jax_ws_client` module"
  include_role:
    name: gen_java_class_from_template
  with_items:
    - src: src/main/java/auth/JSessionIdSsoThreadLocalHolder.java.j2
      dst: "{{ mvn_project_basedir }}/commons_jax_ws_client/src/main/java/{{ group_id_path }}/commons/soap/auth/JSessionIdSsoThreadLocalHolder.java"
    - src: src/main/java/auth/JSessionIdSsoWebFilter.java.j2
      dst: "{{ mvn_project_basedir }}/commons_jax_ws_client/src/main/java/{{ group_id_path }}/commons/soap/auth/JSessionIdSsoWebFilter.java"
    - src: src/main/java/auth/WebContextAuthSoapFilter.java.j2
      dst: "{{ mvn_project_basedir }}/commons_jax_ws_client/src/main/java/{{ group_id_path }}/commons/soap/auth/WebContextAuthSoapFilter.java"
    - src: src/main/java/filter/SoapLogger.java.j2
      dst: "{{ mvn_project_basedir }}/commons_jax_ws_client/src/main/java/{{ group_id_path }}/commons/soap/filter/SoapLogger.java"
    - src: src/main/java/filter/SoapActionRemoval.java.j2
      dst: "{{ mvn_project_basedir }}/commons_jax_ws_client/src/main/java/{{ group_id_path }}/commons/soap/filter/SoapActionRemoval.java"
    - src: src/main/java/filter/SoapThreadLocalHolder.java.j2
      dst: "{{ mvn_project_basedir }}/commons_jax_ws_client/src/main/java/{{ group_id_path }}/commons/soap/filter/SoapThreadLocalHolder.java"
    - src: src/main/java/SoapServiceConfig.java.j2
      dst: "{{ mvn_project_basedir }}/commons_jax_ws_client/src/main/java/{{ group_id_path }}/commons/soap/SoapServiceConfig.java"
    - src: src/main/java/SoapUtils.java.j2
      dst: "{{ mvn_project_basedir }}/commons_jax_ws_client/src/main/java/{{ group_id_path }}/commons/soap/SoapUtils.java"
