---
- name: "Ansible check for `commons_jax_ws_client` module."
  stat:
    path: "{{ mvn_project_basedir }}/commons_jax_ws_client"
  register: commons_jax_ws_client_path

- block:

  - name: Load shared variables
    include_vars: "{{ mvn_project_basedir }}/.ansible/ansible_shared_variables.yml"

  - import_tasks: tasks/commons_jax_ws_client.yml

  when: not commons_jax_ws_client_path.stat.exists

- debug:
    msg:
      - "ERROR: '{{ mvn_project_basedir }}/commons_jax_ws_client' already exist"
      - "       To generate 'commons_jax_ws_client' module first delete the previous one."
  when: commons_jax_ws_client_path.stat.exists