---
- name: "Create `app_config` folder if does not exist"
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  with_items:
    - "{{ app_basedir }}/app_config"

- name: "Generate files into app_config folder"
  template:
    src: "{{ item }}.j2"
    dest: "{{ app_basedir }}/{{ item }}"
    mode: 0644
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    force: yes
  with_items:
    - app_config/pom.xml

- name: "Generate java classes of `app_config` module"
  include_role:
    name: gen_java_class_from_template
  with_items:
    - src: app_config/src/main/java/ConfigFactory.java.j2
      dst: "{{ app_basedir }}/app_config/src/main/java/{{ group_id_path }}/config/commons/ConfigFactory.java"
    - src: app_config/src/main/java/Configs.java.j2
      dst: "{{ app_basedir }}/app_config/src/main/java/{{ group_id_path }}/config/commons/Configs.java"
    - src: app_config/src/main/java/FileConfig.java.j2
      dst: "{{ app_basedir }}/app_config/src/main/java/{{ group_id_path }}/config/commons/FileConfig.java"
    - src: app_config/src/main/java/PropertyKey.java.j2
      dst: "{{ app_basedir }}/app_config/src/main/java/{{ group_id_path }}/config/commons/PropertyKey.java"
    - src: app_config/src/main/java/Configuration.java.j2
      dst: "{{ app_basedir }}/app_config/src/main/java/{{ group_id_path }}/config/Configuration.java"
    - src: app_config/src/main/java/ConfigurationProducer.java.j2
      dst: "{{ app_basedir }}/app_config/src/main/java/{{ group_id_path }}/config/ConfigurationProducer.java"
    - src: app_config/src/main/resources/META-INF/beans.xml
      dst: "{{ app_basedir }}/app_config/src/main/resources/META-INF/beans.xml"
    - src: app_config/src/test/java/AppBaseTest.java.j2
      dst: "{{ app_basedir }}/app_config/src/test/java/{{ group_id_path }}/config/AppBaseTest.java"
    - src: app_config/src/test/java/ConfigFactoryTest.java.j2
      dst: "{{ app_basedir }}/app_config/src/test/java/{{ group_id_path }}/config/commons/ConfigFactoryTest.java"
    - src: app_config/src/test/java/DefaultMethodConfig.java.j2
      dst: "{{ app_basedir }}/app_config/src/test/java/{{ group_id_path }}/config/commons/DefaultMethodConfig.java"
    - src: app_config/src/test/java/NotExistingStringConfig.java.j2
      dst: "{{ app_basedir }}/app_config/src/test/java/{{ group_id_path }}/config/commons/NotExistingStringConfig.java"
    - src: app_config/src/test/java/TestPropertiesConfig.java.j2
      dst: "{{ app_basedir }}/app_config/src/test/java/{{ group_id_path }}/config/commons/TestPropertiesConfig.java"
    - src: app_config/src/test/java/UnsupportedReturnTypeConfig.java.j2
      dst: "{{ app_basedir }}/app_config/src/test/java/{{ group_id_path }}/config/commons/UnsupportedReturnTypeConfig.java"
    - src: "app_config/src/test/resources/test.config.properties.j2"
      dst: "{{ app_basedir }}/app_config/src/test/resources/test.config.properties"

- name: "Add dependencies on 'config' module"
  include_role:
    name: insert_template_after_another
  with_items:
    - path: "{{ app_basedir }}/domain/pom.xml"
      insert_after_template: "{{ role_path }}/templates/app_config/domain/insert_after_template.j2"
      insert_template: "{{ role_path }}/templates/app_config/domain/insert_template.j2"
  loop_control:
    loop_var: cs_itaa_tmpl_item