---
- name: "Create `config` folder if does not exist"
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  with_items:
    - "{{ app_basedir }}/config"

- name: "Copy properties file"
  template:
    src: "config/config.properties.j2"
    dest: "{{ app_basedir }}/config/{{ config_file_name }}"
    mode: 0644
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    force: yes
