---
- name: "Create `commons_config` folder if does not exist"
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  with_items:
    - "{{ mvn_project_basedir }}/commons_config"

- name: "Generate files into commons_config folder"
  template:
    src: "{{ item }}.j2"
    dest: "{{ mvn_project_basedir }}/{{ item }}"
    mode: 0644
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    force: yes
  with_items:
    - commons_config/pom.xml.j2
    - commons_config/README.md.j2
