---
- name: "Loading projects properties"
  include_role:
    name: load_maven_properties

- import_tasks: tasks/app_config.yaml

- import_tasks: tasks/parent_pom.yaml

- import_tasks: tasks/config.yaml

- import_tasks: tasks/rest_api.yaml

- import_tasks: tasks/rest_web.yaml