---
- name: "Add `app_config` module to the parent pom.xml"
  include_role:
    name: insert_text_after_another
  loop_control:
    loop_var: cs_itaa_txt_item
  with_items:
    - path: "{{ app_basedir }}/pom.xml"
      insert_after: |
        <module>commons_test</module>
      insert_text: |4
              <module>app_config</module>

- name: "Update the root `pom.xml` file test testResources"
  include_role:
    name: insert_template_after_another
  with_items:
    - path: "{{ app_basedir }}/pom.xml"
      insert_after_template: "{{ role_path }}/templates/parent_pom/insert_after_template.j2"
      insert_template: "{{ role_path }}/templates/parent_pom/insert_template.j2"
  loop_control:
    loop_var: cs_itaa_tmpl_item