---
- name: "Create `code_quality` folder"
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  with_items:
    - "{{ mvn_project_basedir }}/code_quality"

- name: "Generate findbugs config file"
  template:
    src: "code_quality/findbugs-exclude.xml.j2"
    dest: "{{ mvn_project_basedir }}/code_quality/findbugs-exclude.xml"
    mode: 0644
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    force: yes