---
- name: "Ansible check for `commons_cryptography` module."
  stat:
    path: "{{ mvn_project_basedir }}/commons_cryptography"
  register: commons_cryptography_path

- block:

  - name: Load shared variables
    include_vars: "{{ mvn_project_basedir }}/.ansible/ansible_shared_variables.yml"

  - import_tasks: tasks/commons_cryptography.yml

  when: not commons_cryptography_path.stat.exists

- debug:
    msg:
      - "ERROR: '{{ mvn_project_basedir }}/commons_cryptography' already exist"
      - "       To generate 'commons_cryptography' module first delete the previous one."
  when: commons_cryptography_path.stat.exists